defaults: &defaults
  Ping:
    type: "ping"
    hostname: "$$IP$$"
  SSH:
    type: "port"
    port: "22"
    hostname: "$$IP$$"
vserver_defaults: &vserver_defaults
  <<: *defaults
  DNS: &dns
    type: "dns"
    port: "53"
    hostname: "example.com"
    dns_resolve_server: "$$IP$$"
    dns_resolve_type: "A"
  Node Exporter: &node_exporter
    type: "port"
    port: "9100"
    hostname: "$$IP$$"
  Proxy: &proxy
    type: "port"
    port: "8888"
    hostname: "$$IP$$"
  VPN: &vpn
    type: "port"
    port: "443"
    hostname: "$$IP$$"
monitors:
  us.proxy:
    type: group
    ips:
      v4: "172.16.1.2"
      v6: "2001:0db8:85a3:0000:0000:8a2e:0370:1234"
    monitors:
      <<: *vserver_defaults
  Proxmox:
    type: group
    monitors:
      database:
        type: group
        ips:
          v4: "10.0.0.1"
          v6: "2001:0db8:85a3:0000:0000:8a2e:0370:00db"
        monitors:
          <<: *defaults
          MariaDB:
            type: port
            port: "3306"
            hostname: "$$IP$$"
      powerdns:
        type: group
        ips:
          v4: "10.0.0.2"
          v6: "2001:0db8:85a3:0000:0000:8a2e:0370:0053"
        monitors:
          <<: *defaults
          DNS: *dns
